language: python
python:
  - 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libtidy-dev
install:
    - pip install -r requirements.pip -U --allow-all-external --allow-unverified django-photologue --process-dependency-links
script:
    - coverage run --source='.' mama/sites/mobi/manage_dev.py test mama
