language: python
python:
  - 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libtidy-dev libevent-dev python-dev
install:
    - pip install -r requirements.txt -U
script:
    - py.test -s --ds=test_settings --verbose app
